### ISSUE TITLE
可以选择是否异步加载 highlight.js 以及 katex 吗 ?

### ISSUE THREAD

**Issue by wzdxy** [hinesboy/mavonEditor#20]
项目用到的脚手架是基于 vue-cli 的多次修改版
而且对 webpack 不熟悉 , 已经不知道要怎么改配置文件了.
按照 readme 修改直接会报错:
```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^
TypeError: Path must be a string. Received [ 'vue' ]
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
```
后来改成这个样子:
```
var lang = require('highlight.js-async-webpack/src/file.lang.hljs.js');
entries.back_end= './src/back-end/index.js'; // highlit原始入口
entries.vue='vue';
for (var i = 0; i < lang.length; i++) {
    entries[lang[i]] = 'mavon-editor/dist/js/' + lang[i] + '.js'
}
return entries;
```
好不容易 run dev 成功了, 页面也不显示 , 还有报错

```
This relative module was not found:
* ./src/back-end/index.js in multi ./build/dev-client ./src/back-end/index.js
```

如果可以不用配 webpack 安装好就能直接用就好了, 不是异步加载也没关系

**Comment by hinesboy** [comment]
如果不需要异步加载，可以直接引入mavon-editor使用，控制台会报错找不到hljs文件，不会影响正常运行，设置ishljs = false 既可以去除控制台报错

**Comment by hinesboy** [comment]
如需异步加载，可以参考gh-pages分支中的用法

**Comment by CHENXCHEN** [comment]
`./src/back-end/index.js` 这个是我的样例入口文件，按照实际地址来写。。chunk名也不一定是`back_end`

**Comment by CHENXCHEN** [comment]
你使用的是vue-cli，这个[gh-pages分支](https://github.com/hinesboy/mavonEditor/tree/gh-pages)也许能帮到你

**Comment by wzdxy** [comment]
Thank you all .
Wishing for perfect .
