### ISSUE TITLE
有时候会出现左侧滚动不到顶部的bug

### ISSUE THREAD

**Issue by CatchLife** [hinesboy/mavonEditor#353]
复现步骤：
打开demo： [https://md.zhystar.com/](https://md.zhystar.com/)
先把页面滚动到底部（这一步很重要），粘贴如下markdown
```md
网站验证码突然无法显示，并报如下错误。

```sh
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at java.awt.GraphicsEnvironment.createGE(Unknown Source)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(Unknown Source)
	at java.awt.image.BufferedImage.createGraphics(Unknown Source)
```

网上搜索了一下，在 catalina.sh 里加上一句`-Djava.awt.headless=true \`，问题解决。
经查，出现这种情况一般就是启动 tomcat 的用户无法访问 Xserver，包括 Xserver 没有启动或者没有权限访问.

修改`${TOMCAT_HOME}/bin/catalina.sh`或`${TOMCAT_HOME}/bin/catalina.bat`文件：

在所有类似以下代码：

```sh
    "$_RUNJAVA" $JAVA_OPTS $CATALINA_OPTS \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
      -Djava.security.manager \
      -Djava.security.policy=="$CATALINA_BASE"/conf/catalina.policy \
      -Dcatalina.base="$CATALINA_BASE" \
      -Dcatalina.home="$CATALINA_HOME" \
      -Djava.io.tmpdir="$CATALINA_TMPDIR" \
```

在尾部加上一句：

```sh
-Djava.awt.headless=true \
```

修改后内容如下：

```sh
    exec "$_RUNJAVA" $JAVA_OPTS $CATALINA_OPTS \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
      -Dcatalina.base="$CATALINA_BASE" \
      -Dcatalina.home="$CATALINA_HOME" \
      -Djava.io.tmpdir="$CATALINA_TMPDIR" \
      -Djava.awt.headless=true \
```

1. 什么是 Headless mode？
   Headless 模式是系统的一种配置模式。在该模式下，系统缺少了显示设备、键盘或鼠标。
2. 何时使用和 headless mode？
   Headless 模式虽然不是我们愿意见到的，但事实上我们却常常需要在该模式下工作，尤其是服务器端程序开发者。因为服务器（如提供 Web 服务的主机）往往可能缺少前述设备，但又需要使用他们提供的功能，生成相应的数据，以提供给客户端（如浏览器所在的配有相关的显示设备、键盘和鼠标的主机）。
3. 如何使用和 Headless mode？
   一般是在程序开始激活 headless 模式，告诉程序，现在你要工作在 Headless mode 下，就不要指望硬件帮忙了，你得自力更生，依靠系统的计算能力模拟出这些特性来:
   System.setProperty("java.awt.headless","true");

```

**Comment by CatchLife** [comment]
无语的是github会自动对markdown进行解析，即使用了代码块也不行。。。

**Comment by yueshuiniao** [comment]
同样碰到了这个问题，看了下滚动条是prev.auto-textarea-block这个标签撑起来的，调整下行高简单处理下该元素的宽度可做临时方案（反正编辑和预览区本来就对应不上，影响不大）
![image](https://user-images.githubusercontent.com/17233090/183804135-76e50f0b-7c0f-4a88-aa1a-efc6b2119f8b.png)

在合适的位置加样式覆盖掉原样式
```css
.auto-textarea-block {
    line-height: 1.8 !important;
}
```
