### ISSUE TITLE
[Question] backend.js:949 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by zhangguapipi** [hinesboy/mavonEditor#770]
## 刷新页面就出现下面的报错，百度也没找到办法

backend.js:949 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')
    at registerAppJob (backend.js:949:57)
    at backend.js:937:27
    at run (backend.js:3471:16)
    at backend.js:3475:30
    at onDone (backend.js:3463:11)

**Comment by huzhongqiang1012** [comment]
一样找不到报错问题
