### ISSUE TITLE
[Question] 为什么全局引入后会出现这个问题

### ISSUE THREAD

**Issue by 995509224** [hinesboy/mavonEditor#827]
## 💬 Questions and Help
mavon-editor.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (mavon-editor.js:1:279858)
    at renderComponentRoot (runtime-core.esm-bundler.js:898:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5631:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5759:9)
    at mountComponent (runtime-core.esm-bundler.js:5541:9)
    at processComponent (runtime-core.esm-bundler.js:5499:17)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at mountChildren (runtime-core.esm-bundler.js:5285:13)

**Comment by 2450555169** [comment]
解决了吗 我也遇到了

**Comment by 6lszxz** [comment]
同问

**Comment by lichong951** [comment]
"mavon-editor": "^3.0.0-beta"
有位大佬给解答了

**Comment by coderYxw** [comment]
npm install mavon-editor@next就可以了

**Comment by sports98** [comment]
"vue": "^3.4.15",
"mavon-editor": "^3.0.1",

也是报的这个错误。确认是版本问题么？
