### ISSUE TITLE
[Question] How to solve this problem

### ISSUE THREAD

**Issue by 995509224** [hinesboy/mavonEditor#828]
mavon-editor.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (mavon-editor.js:1:279858)
    at renderComponentRoot (runtime-core.esm-bundler.js:898:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5631:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5759:9)
    at mountComponent (runtime-core.esm-bundler.js:5541:9)
    at processComponent (runtime-core.esm-bundler.js:5499:17)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at mountChildren (runtime-core.esm-bundler.js:5285:13)

**Comment by CeerDecy** [comment]
if your project build by vue3
you should install ^3.0.0-beta
