### ISSUE TITLE
[Bug] XYZ

### ISSUE THREAD

**Issue by marrgit** [hinesboy/mavonEditor#866]
nuxtjs3，引入mavon-editor全局组件、版本：“mavon-editor: "^3.0.1"，

报错

mavon-editor.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$refs')
at Proxy.editableTextarea (mavon-editor.js:1:15117)
at Proxy.<anonymous> (mavon-editor.js:1:8933)

但是使用正常

**Comment by marrgit** [comment]
![snipaste20230519_163022](https://github.com/hinesboy/mavonEditor/assets/37060382/05c76844-ae53-41b7-a5d2-262e6a29cc7d)
![snipaste20230519_162928](https://github.com/hinesboy/mavonEditor/assets/37060382/94dd1a76-ba66-4560-a9e8-9423f1361165)
![snipaste20230519_163041](https://github.com/hinesboy/mavonEditor/assets/37060382/3a5fe225-f5ed-4d7e-8d2a-61fe39ed00c2)

**Comment by freezyh** [comment]
> ![snipaste20230519_163022](https://private-user-images.githubusercontent.com/37060382/239484916-05c76844-ae53-41b7-a5d2-262e6a29cc7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDczOTcsIm5iZiI6MTcwMjU0NzA5NywicGF0aCI6Ii8zNzA2MDM4Mi8yMzk0ODQ5MTYtMDVjNzY4NDQtYWU1My00MWI3LWE1ZDItMjYyZTZhMjljYzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OGQ1ZjQzNDg2ZWU0YjE5OGU2OWE2MGM1OGRkOGQ1NzNhOGIxYTgzYjk5OTRmNjE2ODg1NjhhNzJhOTk1YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rYSemrkakNFF7KvhHYRZp2iEcdKUXcqZn5riA-IlO8E) ![snipaste20230519_162928](https://private-user-images.githubusercontent.com/37060382/239484938-94dd1a76-ba66-4560-a9e8-9423f1361165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDczOTcsIm5iZiI6MTcwMjU0NzA5NywicGF0aCI6Ii8zNzA2MDM4Mi8yMzk0ODQ5MzgtOTRkZDFhNzYtYmE2Ni00NTYwLWE5ZTgtOTQyM2YxMzYxMTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYzE0ZTg4MzMzMGEwZGJkMjYxN2IxNjYxYzY4MmZmY2NmMjliOWU2NzVhNzI3ZWMyYmMzMDc2ZjM5NDljYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p9T8dRzgiIUribwSYTWlzOkSJZvRuTjpODqAhxmlLd0) ![snipaste20230519_163041](https://private-user-images.githubusercontent.com/37060382/239484964-3a5fe225-f5ed-4d7e-8d2a-61fe39ed00c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDczOTcsIm5iZiI6MTcwMjU0NzA5NywicGF0aCI6Ii8zNzA2MDM4Mi8yMzk0ODQ5NjQtM2E1ZmUyMjUtZjVlZC00ZDdlLThkMmEtNjFmZTM5ZWQwMGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NTgxYTJkODVhNGQ1ZGViYzEyNTVmYTJkNjc0NmYyN2MwYzNhZTViNjgzMGNiNGNjNjlhOGZiZjMwYWVlZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PxY20v0anoD0PumNOkFg6PniaCr2J2HaziZ4D4X_E_g)
在Nuxt3中如何正确引入使用？

**Comment by freezyh** [comment]
> ![snipaste20230519_164243](https://private-user-images.githubusercontent.com/37060382/239485240-62fc5a04-6b1d-430a-9738-d52eebc7561d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDczOTcsIm5iZiI6MTcwMjU0NzA5NywicGF0aCI6Ii8zNzA2MDM4Mi8yMzk0ODUyNDAtNjJmYzVhMDQtNmIxZC00MzBhLTk3MzgtZDUyZWViYzc1NjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OTJlNjMwMjhhMGM3MjM4ZmEzM2I2OWY3NDU4NjkyZjllNzk5NzE0ZjQwNWY5NWJkNTkyMGYzNzQyZGExMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eaWuKl2p7FmcG6cIZpZunCu8-Nr7G7F4J8xsZaX88XA)

我在Nuxt3中也出现了类似问题

**Comment by MTTTM** [comment]
web 上面也有这个问题

**Comment by zhouzhouyaya** [comment]
> nuxtjs3，引入mavon-editor全局组件、版本：“mavon-editor: "^3.0.1"，
> 
> 报错
> 
> mavon-editor.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$refs') at Proxy.editableTextarea (mavon-editor.js:1:15117) at Proxy. (mavon-editor.js:1:8933)
> 
> 但是使用正常

我是报错使用也不正常

**Comment by zhouzhouyaya** [comment]
> web 上面也有这个问题

解决了吗

**Comment by zhouzhouyaya** [comment]
> > ![snipaste20230519_164243](https://private-user-images.githubusercontent.com/37060382/239485240-62fc5a04-6b1d-430a-9738-d52eebc7561d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDczOTcsIm5iZiI6MTcwMjU0NzA5NywicGF0aCI6Ii8zNzA2MDM4Mi8yMzk0ODUyNDAtNjJmYzVhMDQtNmIxZC00MzBhLTk3MzgtZDUyZWViYzc1NjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OTJlNjMwMjhhMGM3MjM4ZmEzM2I2OWY3NDU4NjkyZjllNzk5NzE0ZjQwNWY5NWJkNTkyMGYzNzQyZGExMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eaWuKl2p7FmcG6cIZpZunCu8-Nr7G7F4J8xsZaX88XA)
> 
> 我在Nuxt3中也出现了类似问题

解决了吗

**Comment by Larmian** [comment]
> > > ![snipaste20230519_164243](https://private-user-images.githubusercontent.com/37060382/239485240-62fc5a04-6b1d-430a-9738-d52eebc7561d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDczOTcsIm5iZiI6MTcwMjU0NzA5NywicGF0aCI6Ii8zNzA2MDM4Mi8yMzk0ODUyNDAtNjJmYzVhMDQtNmIxZC00MzBhLTk3MzgtZDUyZWViYzc1NjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OTJlNjMwMjhhMGM3MjM4ZmEzM2I2OWY3NDU4NjkyZjllNzk5NzE0ZjQwNWY5NWJkNTkyMGYzNzQyZGExMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eaWuKl2p7FmcG6cIZpZunCu8-Nr7G7F4J8xsZaX88XA)
> > 
> > 
> > 我在Nuxt3中也出现了类似问题
> 
> 解决了吗

我没在vue 的**mounted** 事件里更新文档数据就出现这个问题，把数据更新代码弄到 **mounted** 这个事件里就没出现这个问题

**Comment by zhouzhouyaya** [comment]
我使用tnymce编辑器了。手机端兼容的话比较友好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hinesboy/mavonEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月14日(星期五) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hinesboy/mavonEditor] [Bug] mavon-editor^3.0.1，报错TypeError: Cannot read properties of undefined (reading '$refs') (Issue #866)



      

  
我在Nuxt3中也出现了类似问题
  
解决了吗
  
我没在vue 的mounted 事件里更新文档数据就出现这个问题，把数据更新代码弄到 mounted 这个事件里就没出现这个问题

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  Larmian left a comment (hinesboy/mavonEditor#866)
    

  
我在Nuxt3中也出现了类似问题
  
解决了吗
  
我没在vue 的mounted 事件里更新文档数据就出现这个问题，把数据更新代码弄到 mounted 这个事件里就没出现这个问题

**Comment by zhouzhouyaya** [comment]
我使用tinymce编辑器了，手机端兼容的话也比较友好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hinesboy/mavonEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月14日(星期五) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hinesboy/mavonEditor] [Bug] mavon-editor^3.0.1，报错TypeError: Cannot read properties of undefined (reading '$refs') (Issue #866)



      

  
我在Nuxt3中也出现了类似问题
  
解决了吗
  
我没在vue 的mounted 事件里更新文档数据就出现这个问题，把数据更新代码弄到 mounted 这个事件里就没出现这个问题

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  Larmian left a comment (hinesboy/mavonEditor#866)
    

  
我在Nuxt3中也出现了类似问题
  
解决了吗
  
我没在vue 的mounted 事件里更新文档数据就出现这个问题，把数据更新代码弄到 mounted 这个事件里就没出现这个问题
